name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v2

      # The Flat Action step. We fetch the data in the http_url and save it as downloaded_filename
      - name: Fetch Taiwan COVID Vaccinations
        uses: githubocto/flat@v3
        with:
          http_url: https://web.cw.com.tw/covid-live-updates-2021/data/taiwan-vaccinations.csv
          downloaded_filename: covid-19/taiwan-vaccinations.csv
